server.port=8086

eureka.client.service.url.defaultZone=http://eurekaserver:8761/eureka/

# Student Service Route
spring.cloud.gateway.server.webflux.routes[0].id=student-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://studentservice
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/student/**

# Course Service Route
spring.cloud.gateway.server.webflux.routes[1].id=course-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://courseservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/course/**
